### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by LoveAndHappiness** [axelhzf/todo-angular-es6#1]
Hi Axel,

could you provide some documentation on how to use your package?

After I do 

```
git clone https://github.com/axelhzf/todo-angular-es6.git
```

and 

```
npm install
```

In the root directory and I open the index.html after using "gulp watch" I get this:

http://s30.postimg.org/q8kfs1tn5/capture_001_02072015_143109.jpg

I guess you need to integrate your package to the architecture directory of the todomvc.com git repository, but it would be great, if you package could work out of the box. Can you recommend an alternative working example?

**Comment by axelhzf** [comment]
Hi,

I'm working in a different way at work. I will update this example
